name: Build and Deploy .NET & Angular

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Restore .NET dependencies
      working-directory: ./backend/src
      run: dotnet restore
      
    - name: Build and publish .NET app
      working-directory: ./backend/src
      run: dotnet publish -c Release -o ./publish
      
    - name: .NET app test
      working-directory: ./backend/src
      run: dotnet test --logger trx --results-directory TestResults
      
    - name: .NET test coverage report
      uses: actions/upload-artifact@v2
      with:
        name: published-files
        path: bin/Release/net5.0
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
      
    - name: Install Angular dependencies
      working-directory: ./frontend/ProEventos-App
      run: npm install

    - name: Build Angular app
      working-directory: ./frontend/ProEventos-App
      run: npm run build --prod
