name: Github Pages Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and build
        working-directory: ./frontend/ProEventos-App
        run: npm install && npm run gh-build && cp ./dist/ProEventos-App/index.html ./

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ANGULARTOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: /dist/ProEventos-App # The folder the action should deploy.
